#pragma once


//==================================================================
//scene illumination functions

#define		MAX_LIGHTS		4

uniform float3		 light_pos[MAX_LIGHTS];	
uniform float3		 light_color[MAX_LIGHTS];
//uniform int		 light_type[MAX_LIGHTS];	//2 types: 0 - spot, 1 - directional
												//if light are directional, light_pos, means light direction
//uniform int			 n_lights;					//number of lights

//uniform float3		 light_ambient;


uniform float		 specular_power;


//for the up / down lighting
uniform float3		up_direction;

uniform float3		up_light;		// = float3(0.3, 0.3, 0.3);
uniform float3		down_light;		// = float3(0.1, 0.1, 0.1);

//=================================================================================


struct SIlluminationResult
{
	float3 diffuse;
	float3 specular;
};

SIlluminationResult g_res;

float3	gp_view_dir;

void  illuminate_point(in float3 _light_color, in float3 _light_pos, in float3 _pos, in float3 _norm)
{
	
	float3 l_dir = normalize_func(_light_pos - _pos);
	float  light_i = max( dot( _norm, l_dir) , 0 );	//light intensivity
	g_res.diffuse	+=  _light_color * light_i;

#ifdef USE_SPECULAR

	
	#ifndef FS_LOW_INSTRUCTIONS_LIMIT	//disable in low instruction limit

	//perform specular term
 	float3 V = gp_view_dir;	//view vector
	float3 H = normalize_func(l_dir + V);		//half - angle
	float specular_i = pow(max(dot(H, _norm), 0), specular_power);

	g_res.specular	+=	_light_color * specular_i; 

	#endif
	

#endif

}

//----

void  illuminate_directional(in float3 _light_color, in float3 _light_dir, in float3 _norm)
{
	float  light_i = max( dot( _norm, _light_dir) , 0 );	//light intensivity

//perform specular term..
/*
 //	float3 V = normalize(cam_pos - _pos); //view vector
//	float3 H = normalize(l_dir + V); //half - angle
//	float specular_i = pow(max(dot(H, _norm), 0), shininess);
//	if (light_i <= 0) 
//	specular_i = 0;
//	specular_color += _light_color * specular_i;
*/
	g_res.diffuse	+=  _light_color * light_i;

}

//--------------------------------------------------------------------------------
//illumination position

SIlluminationResult	illuminate(float3 _pos, float3 _norm, float _specular_intensivity_modulator)
{
#ifdef SELF_ILLUMINATION

	SIlluminationResult sr;
	sr.diffuse = float3(1.0, 1.0, 1.0);
	sr.specular = float3(0.0, 0.0, 0.0);
	return sr;

#endif

	// apply hemispherical light 
	float lerp_factor = (dot(_norm, up_direction) + 1) / 2;
	g_res.diffuse = lerp(down_light, up_light, lerp_factor);//light_ambient;
	g_res.specular = float3(0.0, 0.0, 0.0);


#ifdef USE_SPECULAR
	gp_view_dir = normalize_func(cam_pos - _pos);
#endif

//#undef NUM_LIGHTS
///#define NUM_LIGHTS 1

	
#if	  NUM_LIGHTS	== 1
		illuminate_point(light_color[0], light_pos[0], _pos, _norm); 
#elif NUM_LIGHTS	== 2
		illuminate_point(light_color[0], light_pos[0], _pos, _norm); 
		illuminate_point(light_color[1], light_pos[1], _pos, _norm); 
#elif NUM_LIGHTS	== 3
		illuminate_point(light_color[0], light_pos[0], _pos, _norm); 
		illuminate_point(light_color[1], light_pos[1], _pos, _norm); 
		illuminate_point(light_color[2], light_pos[2], _pos, _norm); 
#elif NUM_LIGHTS	== 4
		illuminate_point(light_color[0], light_pos[0], _pos, _norm); 
		illuminate_point(light_color[1], light_pos[1], _pos, _norm); 
		illuminate_point(light_color[2], light_pos[2], _pos, _norm); 
		illuminate_point(light_color[3], light_pos[3], _pos, _norm); 
#endif

#ifdef USE_SPECULAR
	g_res.specular *= _specular_intensivity_modulator;	
#endif

#ifdef SELF_ILLUMINATION_WITH_SPECULAR
	g_res.diffuse = float3(1.0, 1.0, 1.0);	//reset only diffuse color to white
#endif

	return g_res;
}

//=================================================================================
